apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: prod
spec:
  selector:
    app: api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
    name: http
  - port: 443
    targetPort: 443
    name: https
  type: NodePort