apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-development
  namespace: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-development
        image: brunobergamo/pedelogo-catalogo:v1.0.0
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        imagePullPolicy: Always
        env:
        - name: Mongo__Host
          value: "mongo-service.mongo.svc.cluster.local"
        - name: Mongo__User
          value: "mongouser"
        - name: Mongo__Password
          value: "mongopwd"
        - name: Mongo__Port
          value: "27017"
        - name: Mongo__Database
          value: "admin"
